### PR TITLE
Feature/seeds/river

### PR DESCRIPTION
**Pull request by rivyyriv**
Added test date to the following tables,

Phone Numbers, Emails, Education History.

Kate and Saeed will be submitted the other seeds.

Video : [https://www.loom.com/share/296361281ade40b88d5ae0553b21c4d4]

### CODE REVIEW

**Review by ashtilawat — CHANGES_REQUESTED** [review]
Good loom! Can you rebase main and push the commit to your branch. I added github actions to run tests. I want to see if the tests are passing for your PR before I merge it.

**Comment by rivyyriv** [comment]
@ashtilawat23 I rebased main

**Comment by slothwithannuzzi** [comment]
Great job river! The code is neat and concise, and the video does a great job of running through it.

**Review by jciannuzzi — APPROVED** [review]
Great job river! The code is neat and concise, and the video does a great job of running through it.

**Pull request closed without merging**
