### PR TITLE
Feature added - clients && locations seeds implemented

### PR DESCRIPTION
**Pull request by iam-saeed**
https://www.loom.com/share/68e020d89eed485f965df8d839c5e9fb

### CODE REVIEW

**Comment by rivyyriv** [comment]
Nice Job Saeed!! Good idea using the truncate. I didn't think of that.

**Review by ashtilawat — CHANGES_REQUESTED** [review]
Need a loom video walking through your code! Please add it to your description. In your description, include a quick blurb on what work was done and why the work was done. Like the title of the PR!

**Comment by iam-saeed** [comment]
> Need a loom video walking through your code! Please add it to your description. In your description, include a quick blurb on what work was done and why the work was done. Like the title of the PR!

Done!

**Review by xpinero — DISMISSED** [review]
Good job Saeed on the schema properties and placing the truncate. I find the seed data amusing. Thank you for demonstrating the seed files showing up in the database as confirmation.

**Comment by tinomen** [comment]
Whoa! This branch is based on another working branch that has not been merged yet. 

DONT MERGE

It can still be reviewed.

**Comment by miketillman95** [comment]
seeds look good, like the use of truncate as well

**Review by miketillman95 — CHANGES_REQUESTED** [review]
dont think it can merge off the branch

**Review by ashtilawat — CHANGES_REQUESTED** [review]
Can you rebase main before I merge?

**Review by jake-linn — DISMISSED** [review]
Nice job Saeed! Great use of truncate and amusing dummy data with pop culture families. The video was clear and concise and did a good job walking through your code.

**Comment by ashtilawat** [comment]
Duplicate branch.

**Pull request closed without merging**
