### PR TITLE
client tbl schema

### PR DESCRIPTION
**Pull request by miketillman95**
submitting pull but using Johns schema

### CODE REVIEW

**Review by ashtilawat — CHANGES_REQUESTED** [review]
Need a quick loom explaining your code. In your description, please answer the following questions: 1) What work was done? 2) Why was the work done? Also, can you change the name of the PR to something besides the name of the branch?

**Comment by miketillman95** [comment]
https://www.loom.com/share/dcd3985aa36d4f0b876ee5920f1d6566

**Comment by ashtilawat** [comment]
Credit for submitted PR given.

**Comment by katehunnicutt** [comment]
reviewed

**Pull request closed without merging**
