### PR TITLE
Bl 291 add no credit on the be for the finance section of the intake

### PR DESCRIPTION
**Pull request by ChrisJRamirez**
**PR Video**
https://www.loom.com/share/9dcef54131ef4f38aac54d2f1a58ab56

**What work was done/why?**
I made the necessary changes to amend to backend to include no_credit in the finances section. I also added the no_credit to the seeds so that it is more realistic while working on development. I reviewed my code, and also posted to the Slack for review.

**Jira**
https://bloomtechlabs.atlassian.net/jira/software/c/projects/BL/boards/7?modal=detail&selectedIssue=BL-291&assignee=60f8450c8b1a9b006fedea23

### CODE REVIEW

**Review by ashtilawat — CHANGES_REQUESTED** [review]
Why were there 1500+ lines removed from the package-lock.json? Any idea what's going on there. Otherwise, great work. I can merge this if you restore the package-lock that is on main. All you have to do is copy/paste the lock file on main into your branch. Then commit to this PR. It should resolve the issue.

**Review by Valeriusdev — CHANGES_REQUESTED** [review]
I also have the same question about the changes of package-lock.json file. Could you please fix it?

**Review by SJMucho — DISMISSED** [review]

**Comment by derekjpeters** [comment]
@ChrisJRamirez - Have you resolved the 1500 lines removed?

**Comment by derekjpeters** [comment]
@ashtilawat23 I see the commit with the JSON package added, can this be reviewed?

**Review by Valeriusdev — DISMISSED** [review]

**Pull request merged**
