### PR TITLE
Feature/households migrations seeds

### PR DESCRIPTION
**Pull request by stepbystepdayo**
# Description
[loom PR video](https://www.loom.com/share/db8bcb7e47654e4c9ba46cbfe08d2702)
Updated households schema in db diagram.
Made a new households' migration file and updated its seed file to match the updated households schema and fields. 

Future Work: 
`Add disability section into client table`
After confirming the disability section from the stakeholder, I will add a field to store the name of a client's disability to the `clients-table` table.

Fixes #

- What work was done?
Made migration and updated seed for updated households after confirming households fields with project managers.

Updated the schema file in the repo so it can be reflected in our current db-diagram schema.

Added in ethnicities seed (it was missing).

- Why was this work done?
This is updated for fundamental work that needs to be completed before our backend API routes can be written. 
- What feature / user story is it for?
 [Main Story](https://trello.com/c/pHvdRajV/58-create-household-table-and-seeds-for-the-table-afterward)
- Any relevant links or images / screenshots
I used [updated fields](https://docs.google.com/spreadsheets/d/11LHsNPSGqOEhV1O-cuDIzl-LJPIZt07ImQF4j1EiJ-E/edit?usp=sharing) for making migration and seed.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## Change Status

- [ ] Complete, tested, ready to review and merge
- [ ] Complete, but not tested (may need new tests)
- [x] Incomplete/work-in-progress, PR is for discussion/feedback

## Has This Been Tested

- [ ] Yes
- [ ] No
- [x] Not necessary

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] My code has been reviewed by at least one peer
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] There are no merge conflicts

### CODE REVIEW

**Comment by ShariqAli-Dev** [comment]
[Create household table and seeds for the table afterward](https://trello.com/c/pHvdRajV/58-create-household-table-and-seeds-for-the-table-afterward)

**Review by thecuriousones — APPROVED** [review]
Looked over the migration file and the updates to the household seed files and everything looks good and all the changes that were discussed were implemented. A good job overall!

**Review by wild-kard — APPROVED** [review]
Lots of changes to look over here, but it seems that it's mostly seed data! This is great to have, and will allow for more thorough testing in both front and back end.


Good job.

**Review by stkirk — APPROVED** [review]
Look at all that seed data! lot of great stuff here. Once you fix the merge conflict this should be ready to go

**Pull request merged**
