### PR TITLE
Feature/clients disabilities

### PR DESCRIPTION
**Pull request by stepbystepdayo**
# Description

[Loom PR video](https://www.loom.com/share/d753bcc8add54ab4a276d5761f333b2a)
Made a new migration for disability information and Added disabilities_id into clients table 

## Fixes 

- What work was done?
Made a new migration and updated seed and db diagram for disabilities after confirmed the disability information from the stakeholder.
- Why was this work done?
This is updated for fundamental work that needs to be completed before our backend API routes can be written.
- What feature / user story is it for?
Two features: Migrations feature and seeds feature were completed, along with updated fields. 
I did not make Kanban board in Trello.
- Any relevant links or images / screenshots
I used fields for [updated fields](https://docs.google.com/spreadsheets/d/11LHsNPSGqOEhV1O-cuDIzl-LJPIZt07ImQF4j1EiJ-E/edit?usp=sharing) for making migration and seed

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## Change Status

- [ ] Complete, tested, ready to review and merge
- [ ] Complete, but not tested (may need new tests)
- [x] Incomplete/work-in-progress, PR is for discussion/feedback

## Has This Been Tested

- [ ] Yes
- [ ] No
- [x] Not necessary

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] My code has been reviewed by at least one peer
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] There are no merge conflicts

### CODE REVIEW

**Comment by gsauce7** [comment]
Looks good to me.

**Review by thecuriousones — APPROVED** [review]
Everything looks good!

**Review by stkirk — APPROVED** [review]
Great job making these changes to reflect stakeholder feedback. I ran the this branch on my local and everything is working as it should

**Comment by derekjpeters** [comment]
[Test](https://trello.com/c/LZk16XGE/80-test)

**Pull request merged**
